# Generated by Django 2.2.5 on 2020-03-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0003_auto_20200308_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangaseries',
            name='manga_URL',
            field=models.URLField(default=None, unique=True),
        ),
    ]
