# Generated by Django 2.2.5 on 2020-03-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0004_auto_20200308_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangaseries',
            name='manga_URL',
            field=models.URLField(default=None),
        ),
    ]
