# Generated by Django 2.2.5 on 2020-03-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0005_auto_20200308_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangaseries',
            name='image',
            field=models.ImageField(default=None, upload_to='manga_images'),
        ),
        migrations.AlterField(
            model_name='mangaseries',
            name='manga_URL',
            field=models.URLField(default=None, unique=True),
        ),
    ]
