# Generated by Django 2.2.5 on 2020-03-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0009_remove_mangaseries_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangaseries',
            name='latest_chapter',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
