# Generated by Django 2.2.5 on 2020-03-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0010_mangaseries_latest_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangaseries',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='manga_images/'),
        ),
    ]
